# Generated by Django 4.0.5 on 2022-07-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hodnota_atributu_id', models.IntegerField()),
                ('nazev_atributu_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=200)),
                ('kod', models.CharField(blank=True, max_length=200)),
                ('zobrazit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hodnota', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=200)),
                ('obrazek_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obrazek', models.URLField()),
                ('nazev', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cena', models.CharField(max_length=200)),
                ('mena', models.CharField(blank=True, max_length=200)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute', models.IntegerField()),
                ('product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.IntegerField()),
                ('obrazek_id', models.IntegerField()),
                ('nazev', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='api.catalog')),
                ('products_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='api.catalog')),
            ],
        ),
    ]
